spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: h2
    password: psw_h2_nk
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
